name: my_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  fl_chart: ^0.55.0
  table_calendar: ^3.0.9
  stop_watch_timer: ^3.1.1
  flutter_countdown_timer: ^4.1.0
  precision_stopwatch: ^1.0.2
  gg_fake_stopwatch: ^1.2.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  google_generative_ai: ^0.1.0
  file_picker: ^4.6.1
  google_fonts: ^6.1.0
  image_picker: ^0.8.6
  firebase_core: ^2.24.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo (2).png
    - assets/hero.jpg
    - assets/hospital1.png
    - assets/hospital2.jpg
    - assets/hospital3.jpg
    - assets/doctor1.jpg
    - assets/doctor2.jpg
    - assets/doctor3.jpg
    - assets/doctor9.jpg